workspace:
  base: /srv/app
  path: src/code.gitea.io/git

clone:
  git:
    image: plugins/git:1
    # Tests require the entire history (for some reason)
    #depth: 50
    tags: true

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    commands:
      - git update-ref refs/heads/test HEAD
      - git --version
      - make clean
      - make vet
      - make lint
      - make test
      - make build

  testing-1-7:
    image: webhippie/golang:edge
    pull: true
    environment:
      - GITEA_GIT_PATH="/foo/local/bin/git"
    commands:
      - git update-ref refs/heads/test HEAD
      - apk update
      - apk add autoconf zlib-dev tcl
      - mkdir -p /foo/local
      - make test-install-git-1-7
      - /foo/local/bin/git --version
      - make clean
      - make vet
      - make lint
      - make test
      - make build

  # coverage:
  #   image: plugins/coverage:1
  #   pull: true
  #   secrets: [ github_token ]
  #   server: https://coverage.gitea.io

  discord:
    image: appleboy/drone-discord:1.0.0
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]
